### ISSUE TITLE
Odd highlighting with HCL

### ISSUE THREAD

**Issue by PicoSushi** [yoshuawuyts/vmd#121] opened 2018-05-23 06:19 UTC
When I wrote markdown with contains HCL code and viewed with vmd, the highlighting was odd as below:
![vmd-ss2](https://user-images.githubusercontent.com/37548801/40406627-5f42be92-5e9c-11e8-9a19-503413215a79.png)

As you can see, the first `resource` keyword didn't highlighted.

Markdown for reproduce is this:

First `resource` doesn't be highlighted!
```hcl
resource "aws_instance" "example" {
  ami = "ami-40d28157"
  instance_type = "t2.micro"
}

resource "dnsimple_record" "example" {
  domain = "example.com"
  name   = "test"
  value  = "${aws_instance.example.public_ip}"
}
```

If comment line inserted, first `resource` also highlighted.
```hcl
# blah blah blah
resource "aws_instance" "example" {
  ami = "ami-40d28157"
  instance_type = "t2.micro"
}

resource "dnsimple_record" "example" {
  domain = "example.com"
  name   = "test"
  value  = "${aws_instance.example.public_ip}"
}
```

**Comment by maxkueng** [comment] 2018-05-27 12:05
Hi. Thanks for reporting the issue!

vmd uses [highlight.js](https://github.com/isagalaev/highlight.js) (indirectly via remark-highlight.js -> lowlight -> highlight.js).

The reported problem seems to be an issue in highlight.js. You can try to file an issue there. If it gets fixed and the dependencies in between get updated it will eventually land in vmd.

I'm going to close this as there isn't really anything I can do and the issue is not significant enough to switch to a different highlighting library.

**Closed by maxkueng** 2018-05-27 12:05 UTC
