### ISSUE TITLE
Two colons in URL confuses vmd while github is ok

### ISSUE THREAD

**Issue by hexmode** [yoshuawuyts/vmd#102] opened 2017-07-29 21:19 UTC
Example file: https://github.com/seanchen/CategoryWatch/blob/master/README.md

Note the rendering of the url: https://www.mediawiki.org/wiki/Extension:CategoryWatch

In vmd, I get 
![image](https://user-images.githubusercontent.com/43581/28748290-0629a85c-7482-11e7-92d6-999af6b48e2e.png)

**Comment by josephfrazier** [comment] 2017-08-08 14:30
I think this is the same bug as https://github.com/yoshuawuyts/vmd/issues/101

**Comment by hexmode** [comment] 2017-08-08 15:04
Agreed.

**Comment by maxkueng** [comment] 2017-08-09 14:20
Closing as duplicate of #101

**Closed by maxkueng** 2017-08-09 14:20 UTC

**Comment by maxkueng** [comment] 2017-08-10 16:29
It's fixed in vmd 1.29.2

**Comment by hexmode** [comment] 2017-08-11 20:53
confirmed, tyvm
