### ISSUE TITLE
fresh install displays contents of `main/main.js`

### ISSUE THREAD

**Issue by ungoldman** [yoshuawuyts/vmd#88] opened 2016-08-08 20:28 UTC
### expected

After installing with `npm -g vmd`, running `vmd readme.md` will open a window with a markdown preview of my readme.

### actual

running `vmd readme.md` or even `vmd` without arguments, I get the following:

![screen shot 2016-08-08 at 1 23 45 pm](https://cloud.githubusercontent.com/assets/427322/17494871/7a81ad64-5d6b-11e6-8140-fc5ecc0a775b.png)

I can open a file to preview with the app menu (Command+O) after the program has opened, but initial state is always the contents of `main/main.js` from the `vmd` repo as far as I can tell. I haven't cloned it locally so it's definitely coming from inside the electron app.

**Comment by maxkueng** [comment] 2016-08-08 22:21
Hi! I just uninstalled vmd and reinstalled it from npm but I can't reproduce the problem. Do you get any console output about an error? And if you run vmd with the devtools open (`vmd --devtools=true`) are there any errors?

I'm using Linux so I can't test it on a Mac.

It might have something to do with fc26bda (was refactored in 0fc0e35). If you have time, could you play with the numbers on [line 6](https://github.com/yoshuawuyts/vmd/blob/0fc0e35c91a02415264bd70219be61054ec96f57/main/config.js#L6) by trying to change the second number (currently `2`) to e.g. `1` or `0` or `3` and also `concole.log()` the `isPackaged` variable? `isPackaged` should be `false` if installed from npm.

**Comment by arilotter** [comment] 2016-08-09 14:06
I'm getting `isPackaged === true` when installed from NPM. Setting it to `false` makes VMD work as expected.

**Comment by maxkueng** [comment] 2016-08-09 17:15
Thanks @arilotter! I'll try to find a different way to figure out whether vmd is running as a packaged app and hopefully publish a fix in a few hours.

**Comment by maxkueng** [comment] 2016-08-10 13:50
`vmd@1.26.4` is on npm. Would be great if you could give quick feedback if this also works on your computer so that I can close the issue.

**Comment by maxkueng** [comment] 2016-08-10 13:51
Changed my mind. I'm closing the issue. Please reopen if the problem persists.

**Closed by maxkueng** 2016-08-10 13:51 UTC

**Comment by ungoldman** [comment] 2016-08-10 17:58
Reinstalled from `npm`, looks to be working fine now! Tested running without arguments and opening a readme from the command line. Thanks @maxkueng & @arilotter!
